# Generated by Django 5.2.16 on 2026-07-12 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('custom_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset_categories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, null=True, unique=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('reserved', 'Reserved'), ('under_maintenance', 'Under Maintenance'), ('lost', 'Lost'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='available', max_length=20)),
                ('is_bookable', models.BooleanField(default=False)),
                ('custom_field_values', models.JSONField(default=dict)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='org.department')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
    ]
