# Generated by Django 5.2.16 on 2026-07-12 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetflow_auth', '0002_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(db_column='booked_by', on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='assetflow_auth.user')),
                ('resource_asset', models.ForeignKey(db_column='resource_asset_id', on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='assets.asset')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
