# Generated by Django 5.2.16 on 2026-07-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('assetflow_auth', '0002_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='asset',
            field=models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.RESTRICT, related_name='allocations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_approved', to='assetflow_auth.user'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='asset',
            field=models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_requests', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requested_by',
            field=models.ForeignKey(db_column='requested_by', on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_requests_made', to='assetflow_auth.user'),
        ),
    ]
