# Generated by Django 5.2.16 on 2026-07-12 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetflow_auth', '0002_initial'),
        ('assets', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAuditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetflow_auth.user')),
            ],
            options={
                'db_table': 'audit_auditors',
            },
        ),
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('scope_location', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('auditors', models.ManyToManyField(related_name='assigned_audit_cycles', through='audit.AuditAuditor', to='assetflow_auth.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audit_cycles', to='assetflow_auth.user')),
                ('scope_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cycles', to='org.department')),
            ],
            options={
                'db_table': 'audit_cycles',
            },
        ),
        migrations.AddField(
            model_name='auditauditor',
            name='audit_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.auditcycle'),
        ),
        migrations.CreateModel(
            name='AuditDiscrepancyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_json', models.TextField()),
                ('audit_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_reports', to='audit.auditcycle')),
            ],
            options={
                'db_table': 'audit_discrepancy_reports',
            },
        ),
        migrations.AlterUniqueTogether(
            name='auditauditor',
            unique_together={('audit_cycle', 'user')},
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('missing', 'Missing'), ('damaged', 'Damaged')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='assets.asset')),
                ('audit_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.auditcycle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_audit_items', to='assetflow_auth.user')),
            ],
            options={
                'db_table': 'audit_items',
                'unique_together': {('audit_cycle', 'asset')},
            },
        ),
    ]
