# Generated by Django 5.2.16 on 2026-07-12 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetflow_auth', '0002_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('technician_assigned', 'Technician Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('technician_name', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_approved', to='assetflow_auth.user')),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_requests', to='assets.asset')),
                ('raised_by', models.ForeignKey(db_column='raised_by', on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_requests_raised', to='assetflow_auth.user')),
            ],
            options={
                'db_table': 'maintenance_requests',
            },
        ),
    ]
