<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="data">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="auth">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="access_token" type="xs:string"/>
                    <xs:element name="refresh_token" type="xs:string"/>
                    <xs:element name="expires_in" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
